import * as React from "react";
import { DataGrid } from "@material-ui/data-grid";

const columns = [
  { field: "id", headerName: "S.No", width: 110 },
  {
    field: "BusinessName",
    headerName: "Business Name",
    width: 180,
    editable: true,
  },
  {
    field: "ContactPersonName",
    headerName: "Contact Person Name",
    width: 220,
    editable: true,
  },
  {
    field: "ContactPersonNumber",
    headerName: "Contact Person No",
    width: 210,
    editable: true,
  },
  {
    field: "Email",
    headerName: "Email",
    sortable: true,
    width: 160,
  },
  {
    field: "Website",
    headerName: "Website",
    sortable: true,
    width: 160,
  },
  {
    field: "Category",
    headerName: "Category",
    sortable: true,
    width: 160,
  },
  {
    field: "DataSource",
    headerName: "DataSource",
    sortable: true,
    width: 160,
  },
  {
    field: "Status",
    headerName: "Status",
    sortable: true,
    width: 160,
  },
  {
    field: "Remarks",
    headerName: "Remarks",
    sortable: true,
    width: 160,
  },
  {
    field: "AppointmentDate",
    headerName: "Appointment Date",
    sortable: true,
    width: 200,
  },
  {
    field: "ClientRequirement",
    headerName: "Client Requirement",
    sortable: true,
    width: 210,
  },
  {
    field: "FollowUpDate",
    headerName: "FollowUp Date",
    sortable: true,
    width: 180,
  },
  {
    field: "Qoutation",
    headerName: "Qoutation",
    sortable: true,
    width: 160,
  },
  {
    field: "actions",
    headerName: "Actions",
    sortable: true,
    width: 160,
  },
];

const rows = [
  {
    id: 1,
    BusinessName: "Jon",
    ContactPersonName: "Jon ",
    ContactPersonNumber: "63665",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 2,
    BusinessName: "Lannister",
    ContactPersonName: "Cersei",
    ContactPersonNumber: "42",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 3,
    BusinessName: "Lannister",
    ContactPersonName: "Jaime",
    ContactPersonNumber: "45",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 4,
    BusinessName: "Stark",
    ContactPersonName: "Arya",
    ContactPersonNumber: "16",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 5,
    BusinessName: "Targaryen",
    ContactPersonName: "Daenerys",
    ContactPersonNumber: "",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 6,
    BusinessName: "Melisandre",
    ContactPersonName: null,
    ContactPersonNumber: "654645",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 7,
    BusinessName: "Clifford",
    ContactPersonName: "Ferrara",
    ContactPersonNumber: "44",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 8,
    BusinessName: "Frances",
    ContactPersonName: "Rossini",
    ContactPersonNumber: "36",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
  {
    id: 9,
    BusinessName: "Roxie",
    ContactPersonName: "Harvey",
    ContactPersonNumber: "65",
    Email: "email",
    Website: "example.com",
    Category: "school",
    DataSource: "online",
    Status: "followup",
    Remarks: "commment",
    AppointmentDate: "25/2/2020",
    ClientRequirement: "something",
    FollowUpDate: "25/2/2020",
    Qoutation: "5646",
    actions: "delete",
  },
];

export default function DataTable() {
  return (
    <div style={{ height: 400, width: "100%" }}>
      <DataGrid
        rows={rows}
        columns={columns}
        pageSize={20}
        rowHeight={40}
        checkboxSelection
        disableSelectionOnClick
        // showCellRightBorder
        showColumnRightBorder
        density='compact'
        // loading
      />
    </div>
  );
}
